export default [
  "When you see it...",
  "That moment when...",
  "Can't even...",
  "Vibe check!",
  "Say less.",
  "No thoughts, head empty.",
  "Mood.",
  "Absolutely not.",
  "This is fine.",
  "Why tho?",
  "Yikes!",
  "LOL nope",
  "Me, pretending to care",
  "Send help",
  "Sassy mode activated",
];
